import { db } from "../core/db.js?v=43ebd473";
import { kpis, serieDiaria, porEntidade, custosExtrasNoPeriodo } from "../core/metrics.js?v=43ebd473";
import { cartao, tabela, abrirFormulario, vazio, kpi, abas, graficoLinhas, barrasH } from "../core/ui.js?v=43ebd473";
import { esc, brl, inteiro, pct, mult, dataBR, dataCurta } from "../core/format.js?v=43ebd473";
import { bannerDemo, btnNovo } from "./comum.js?v=43ebd473";
import { rotulo as rotuloOpcao } from "../core/schema.js?v=43ebd473";
import { podeEditar } from "../core/auth.js?v=43ebd473";

let aba = "dia";
const colsBase = [{ key: "spend", label: "Investimento", tipo: "num", valor: (l) => l.k.spend, fmt: brl }, { key: "revenue", label: "Faturamento", tipo: "num", valor: (l) => l.k.revenue, fmt: brl }, { key: "cost", label: "Custo produtos", tipo: "num", valor: (l) => l.k.cost, fmt: brl }, { key: "taxas", label: "Taxas+frete", tipo: "num", valor: (l) => l.k.fees + l.k.shipping, fmt: brl }, { key: "gross", label: "Lucro bruto", tipo: "num", valor: (l) => l.k.gross_profit, fmt: brl }, { key: "net", label: "Lucro líquido", tipo: "num", valor: (l) => l.k.gross_profit - l.k.spend, fmt: brl }, { key: "roas", label: "ROAS", tipo: "num", valor: (l) => l.k.roas, fmt: mult }, { key: "roi", label: "ROI", tipo: "num", valor: (l) => l.k.roi, fmt: (v) => pct(v) }];

export default {
  id: "financeiro", titulo: "Financeiro", icone: "🏦",
  render(root, ctx) {
    const iv = ctx.iv, k = kpis(iv), serie = serieDiaria(iv), extras = custosExtrasNoPeriodo(iv);
    let corpo = "";
    if (aba === "dia") corpo = cartao("Por dia", graficoLinhas({ rotulos: serie.map((d) => dataCurta(d.date)), series: [{ nome: "Faturamento", cor: "var(--verde)", valores: serie.map((d) => d.revenue) }, { nome: "Investimento", cor: "var(--acento)", valores: serie.map((d) => d.spend) }, { nome: "Lucro líquido", cor: "var(--ciano)", valores: serie.map((d) => d.gross_profit - d.spend) }], formato: "money" }) + tabela("fin-dia", { colunas: [{ key: "date", label: "Dia", fmt: dataBR }, { key: "spend", label: "Investimento", tipo: "num", fmt: brl }, { key: "revenue", label: "Faturamento", tipo: "num", fmt: brl }, { key: "cost", label: "Custo produtos", tipo: "num", fmt: brl }, { key: "taxas", label: "Taxas+frete", tipo: "num", valor: (d) => d.fees + d.shipping, fmt: brl }, { key: "gross_profit", label: "Lucro bruto", tipo: "num", fmt: brl }, { key: "traf", label: "Custo de tráfego", tipo: "num", valor: (d) => d.spend, fmt: brl }, { key: "net", label: "Lucro líquido est.", tipo: "num", valor: (d) => d.gross_profit - d.spend, fmt: brl }, { key: "roas", label: "ROAS", tipo: "num", fmt: mult }], linhas: serie.filter((d) => d.spend || d.revenue), ordem: "date" }));
    else if (aba === "campanha") corpo = cartao("Por campanha", tabela("fin-camp", { colunas: [{ key: "nome", label: "Campanha", render: (l) => `<a href="#/campanhas/${l.id}">${esc(l.nome)}</a>` }, ...colsBase], linhas: porEntidade(iv, "campaign"), ordem: "revenue" }));
    else if (aba === "produto") corpo = cartao("Por produto", tabela("fin-prod", { colunas: [{ key: "nome", label: "Produto", render: (l) => `<a href="#/produtos/${l.id}">${esc(l.nome)}</a>` }, { key: "sales", label: "Vendas", tipo: "num", valor: (l) => l.k.sales, fmt: inteiro }, ...colsBase], linhas: porEntidade(iv, "product"), ordem: "revenue" }));
    else if (aba === "plataforma") { const pl = porEntidade(iv, "platform"); corpo = cartao("Por plataforma", barrasH(pl.map((p) => ({ nome: p.nome, valor: p.k.revenue, cor: "var(--verde)", extra: "investido " + brl(p.k.spend) + " · ROAS " + mult(p.k.roas) })), { fmt: brl }) + "<div style='height:12px'></div>" + tabela("fin-plat", { colunas: [{ key: "nome", label: "Plataforma" }, { key: "leads", label: "Leads", tipo: "num", valor: (l) => l.k.leads_base, fmt: inteiro }, { key: "sales", label: "Vendas", tipo: "num", valor: (l) => l.k.sales, fmt: inteiro }, ...colsBase], linhas: pl, ordem: "revenue" })); }
    else corpo = cartao("Outros custos de tráfego (ferramentas, agência, produção)", (podeEditar() ? `<button class="btn btn-pq btn-primario" data-novo-custo style="margin-bottom:10px">➕ Lançar custo</button>` : "") + tabela("fin-extra", { colunas: [{ key: "date", label: "Data", fmt: dataBR }, { key: "type", label: "Tipo", render: (r) => esc(rotuloOpcao("cost_type", r.type)) }, { key: "description", label: "Descrição" }, { key: "value", label: "Valor", tipo: "num", fmt: brl }, { key: "acao", label: "", render: (r) => podeEditar() ? `<button class="btn btn-pq" data-editar-custo="${r.id}">✏️</button>` : "" }], linhas: extras, ordem: "date", vazioTxt: "Nenhum custo extra no período." }));
    root.innerHTML = `${bannerDemo()}<div class="pagina-cab"><div><h1>Financeiro do tráfego</h1><p class="sub">Investimento, faturamento, custo dos produtos e lucro no período</p></div></div>
      <div class="kpis">${kpi({ rotulo: "Investimento em anúncios", valor: brl(k.spend), destaque: true })}${kpi({ rotulo: "Faturamento", valor: brl(k.revenue), destaque: true })}${kpi({ rotulo: "Custo dos produtos", valor: brl(k.cost) })}${kpi({ rotulo: "Descontos dados", valor: brl(k.discount) })}${kpi({ rotulo: "Taxas e frete", valor: brl(k.fees + k.shipping) })}${kpi({ rotulo: "Lucro bruto", valor: brl(k.gross_profit), sub: "já sem mercadoria, taxas e frete" })}${kpi({ rotulo: "Custo de tráfego total", valor: brl(k.spend + k.extra_costs), sub: k.extra_costs ? "inclui " + brl(k.extra_costs) + " de outros custos" : "" })}${kpi({ rotulo: "Lucro líquido estimado", valor: brl(k.net_profit), destaque: true })}${kpi({ rotulo: "ROAS", valor: mult(k.roas) })}${kpi({ rotulo: "ROI", valor: pct(k.roi) })}</div>
      ${abas([["dia", "Por dia"], ["campanha", "Por campanha"], ["produto", "Por produto"], ["plataforma", "Por plataforma"], ["extras", "Outros custos"]], aba)}${corpo}`;
    root.querySelectorAll("[data-aba]").forEach((b) => b.addEventListener("click", () => { aba = b.dataset.aba; ctx.rerender(); }));
    const n = root.querySelector("[data-novo-custo]"); if (n) n.addEventListener("click", () => abrirFormulario("financial_records", null, { onSave: ctx.rerender }));
    root.querySelectorAll("[data-editar-custo]").forEach((b) => b.addEventListener("click", () => abrirFormulario("financial_records", b.dataset.editarCusto, { onSave: ctx.rerender, onDelete: ctx.rerender })));
  },
};
