// Formatação pt-BR e utilidades pequenas.
export const esc = (s) => String(s == null ? "" : s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
export const semAcento = (s) => String(s || "").normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase();
export const num = (v) => { const n = Number(v); return isFinite(n) ? n : 0; };
export const brl = (v, casas = 2) => (v == null || !isFinite(v)) ? "—" : "R$ " + Number(v).toLocaleString("pt-BR", { minimumFractionDigits: casas, maximumFractionDigits: casas });
export const brlCurto = (v) => (v == null || !isFinite(v)) ? "—" : Math.abs(v) >= 1e6 ? "R$ " + (v / 1e6).toLocaleString("pt-BR", { maximumFractionDigits: 2 }) + " mi" : Math.abs(v) >= 1e4 ? "R$ " + (v / 1e3).toLocaleString("pt-BR", { maximumFractionDigits: 1 }) + " mil" : brl(v);
export const inteiro = (v) => (v == null || !isFinite(v)) ? "—" : Math.round(v).toLocaleString("pt-BR");
export const dec = (v, c = 2) => (v == null || !isFinite(v)) ? "—" : Number(v).toLocaleString("pt-BR", { minimumFractionDigits: c, maximumFractionDigits: c });
export const pct = (v, c = 1) => (v == null || !isFinite(v)) ? "—" : dec(v * 100, c) + "%";
export const mult = (v) => (v == null || !isFinite(v)) ? "—" : dec(v, 2) + "x";
export const dataBR = (iso) => { if (!iso) return "—"; const p = String(iso).slice(0, 10).split("-"); return p.length === 3 ? `${p[2]}/${p[1]}/${p[0]}` : iso; };
export const dataCurta = (iso) => { if (!iso) return "—"; const p = String(iso).slice(0, 10).split("-"); return `${p[2]}/${p[1]}`; };
export const horaCurta = (iso) => { if (!iso) return ""; const d = new Date(iso); return d.toLocaleDateString("pt-BR", { day: "2-digit", month: "2-digit" }) + " " + d.toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" }); };
export const agora = () => new Date().toISOString();
export const hoje = () => { const d = new Date(); return new Date(d.getTime() - d.getTimezoneOffset() * 60000).toISOString().slice(0, 10); };
export const somaDias = (iso, n) => { const d = new Date(iso + "T12:00:00Z"); d.setUTCDate(d.getUTCDate() + n); return d.toISOString().slice(0, 10); };
export const diasEntre = (a, b) => Math.round((new Date(b + "T12:00:00Z") - new Date(a + "T12:00:00Z")) / 86400000);
export const diaSemana = (iso) => ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"][new Date(iso + "T12:00:00Z").getUTCDay()];
export const NOMES_DIAS = ["Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"];
export const NOMES_MESES = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"];
export const uid = () => Date.now().toString(36) + Math.random().toString(36).slice(2, 9);
export const telLimpo = (t) => String(t || "").replace(/\D/g, "");
export const waLink = (t) => { let n = telLimpo(t); if (!n) return ""; if (n.length <= 11) n = "55" + n; return "https://wa.me/" + n; };
export const semanaISO = (iso) => { const d = new Date(iso + "T12:00:00Z"); const dia = d.getUTCDay() || 7; d.setUTCDate(d.getUTCDate() + 4 - dia); const ano = d.getUTCFullYear(); const ini = new Date(Date.UTC(ano, 0, 1)); const n = Math.ceil((((d - ini) / 86400000) + 1) / 7); return `${ano}-W${String(n).padStart(2, "0")}`; };
export const variacao = (atual, anterior) => (anterior == null || atual == null || !isFinite(atual) || !isFinite(anterior) || anterior === 0) ? null : (atual - anterior) / Math.abs(anterior);
export const seta = (v) => v == null ? "" : v > 0.005 ? "↑" : v < -0.005 ? "↓" : "=";
export const clamp = (v, a, b) => Math.max(a, Math.min(b, v));
export const b64utf8 = (s) => btoa(encodeURIComponent(s).replace(/%([0-9A-F]{2})/g, (_, p) => String.fromCharCode(parseInt(p, 16))));
export const utf8b64 = (b) => decodeURIComponent(Array.prototype.map.call(atob(b.replace(/\n/g, "")), (c) => "%" + ("00" + c.charCodeAt(0).toString(16)).slice(-2)).join(""));
